name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./Watchdog/Watchdog.ProxyListener/
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Install dependencies
      working-directory: ${{env.working-directory}}
      run: dotnet restore
    - name: Build
      working-directory: ${{env.working-directory}}
      run: dotnet build --configuration Release --no-restore